<?php
// This file is auto-generated by install.sh and written to webui/config.php.
// Kept here only as a reference for what the generated file looks like.
return [
    'admin_user'    => 'admin',
    'admin_hash'    => '$2y$10$REPLACE_WITH_password_hash_OUTPUT',
    'wg_iface'      => 'wg0',
    'wg_conf'       => '/etc/wireguard/wg0.conf',
    'wg_clients_dir'=> '/etc/wireguard-clients',
    'wg_subnet'     => '10.66.0.0/24',
    'wg_server_ip'  => '10.66.0.1',
    'wg_port'       => 51820,
    'server_pub_ip' => '203.0.113.10',
    'server_pubkey' => 'REPLACE_ME',
    'pihole_db'     => '/etc/pihole/pihole-FTL.db',
    'pihole_admin_url' => 'http://10.66.0.1/admin/',
    'allowed_cidr'  => '10.66.0.0/24',
    'session_name'  => 'dnsvpnui_sess',
];
